CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	avatar VARCHAR(255) NOT NULL
);

CREATE TABLE films(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name_film VARCHAR(255) NOT NULL,
	ganre VARCHAR(255) NOT NULL,
	year_release YEAR NOT NULL,
	country VARCHAR(255) NOT NULL,
	poster_film VARCHAR(255) NOT NULL
);

CREATE TABLE serials(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name_serial VARCHAR(255) NOT NULL,
	ganre VARCHAR(255) NOT NULL,
	year_release YEAR NOT NULL,
	country VARCHAR(255) NOT NULL,
	poster_serial VARCHAR(255) NOT NULL
);

CREATE TABLE favorites(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	film_id INT NULL,
	serial_id INT NULL,
	added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (film_id) REFERENCES films(id),
	FOREIGN KEY (serial_id) REFERENCES serials(id)
);
